# Generated by Django 2.2.2 on 2020-05-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product6',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Burger'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Pizza'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Chinese'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Beverages'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Sandwich'),
        ),
    ]
