# Generated by Django 2.2.2 on 2020-05-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('category', models.CharField(choices=[('0', 'Canteen_food'), ('1', 'Product'), ('2', 'Health'), ('3', 'Inspiration'), ('4', 'College_news')], max_length=2)),
                ('slug', models.SlugField(max_length=270)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
